CONTIKI_PROJECT = client server forwarder
all: $(CONTIKI_PROJECT)

CONTIKI = ../../..
include $(CONTIKI)/Makefile.identify-target

MODULES += os/services/akes
MAKE_MAC = MAKE_MAC_CSL

include $(CONTIKI)/Makefile.include
